apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-app-ingress
spec:
  rules:
  - host: host-name-here
    http:
      paths:
      - backend:
          service:
            name: java-app-service
            port: 
              number: 8080
        pathType: Exact
        path: /
  ingressClassName: nginx
