apiVersion: v1
kind: Secret
type: Opaque
metadata: 
  name: slack-auth
  namespace: monitoring
data:
  slack_url: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDA2NEI2OUNYRFovQjA2QlcwMUtOOU0vQmFFTEFrM2RGSGoxR0paYm13T05EMzZ2
